### ISSUE TITLE
Wikikgv2 Model Training is Hanging

### ISSUE THREAD

**Issue by HarryShomer** [google-research/smore#11] opened 2022-10-04 17:59 UTC
Hi, 

I'm having an issue where the model gets stuck while training. It typically happens early in the first epoch. Below is an example when running the `smore/training/vec_scripts/train_shallow_wikikgv2.sh` (unmodified sans the GPUs) on 4 NVIDIA RTX A6000 50GB GPUs.

![model_stuck](https://user-images.githubusercontent.com/25351167/193891643-4e52d226-2a7a-4d3c-82ee-d90eb15ec44f.png)

It hangs forever unless I stop it with a keyboard interrupt. Doing so yields the following traceback (I only post a portion because it's very long and repetitive).

![model_traceback](https://user-images.githubusercontent.com/25351167/193891854-e401d0e2-c18b-4fcd-a8c5-48ea5530c83d.png)

It seems like something is happening in the multiprocessing as it's hanging when sharing messages between processes.

Any help would be appreciated! @hyren 

Thanks,
Harry

**Comment by hyren** [comment] 2022-10-09 02:30
Hi, this does not seem to be related to the smore repo. Here is an instruction I found, can you please check?
https://www.rdmamojo.com/2012/05/18/libibverbs/

**Comment by HarryShomer** [comment] 2022-10-11 20:07
That doesn't seem to be the issue.

I tried seting up libibverbs, and while the warnings went away, the code is still hanging.

![smore_hang](https://user-images.githubusercontent.com/25351167/195188173-26ffc686-30aa-4f9f-94ef-19b73ac4f81f.png)

**Comment by hyren** [comment] 2022-10-11 21:14
Hi, can you say more about the details of the environment?

**Comment by HarryShomer** [comment] 2022-10-11 21:43
Sure. Here's some basic info. Let me know if you would like anything else.
```
OS: Ubuntu 20.04.5 LTS
CUDA: 11.6.124
GPU(s): NVIDIA RTX A6000
Python: 3.9.12
PyTorch: 1.12.1
```

**Comment by Hanjun-Dai** [comment] 2022-10-11 21:49
Hi there, sorry for the inconvenience, could you please quickly try with only 1 gpu, and see if it still hangs? We are trying to figure out whether it is due to gpu-gpu communication, or the c++ sampler we used.

**Comment by HarryShomer** [comment] 2022-10-11 21:57
Sorry, I should have been clearer in my initial comment. The code doesn't hang when running with just one GPU. This only occurs when using multiple GPUs.

**Comment by Juanhui28** [comment] 2022-10-12 05:58
We tried one gpu again, actually it still hangs. Sorry for the inconvenience.

**Comment by Hanjun-Dai** [comment] 2022-10-12 07:26
Hi there,

Could you please kindly pull the latest code in the **wikikgv2** branch, and add `--train_async_rw=False` to your script and try again? Since I'm unable to reproduce your issue, I'd like to see whether this would temporarily resolve the issue.

**Comment by Juanhui28** [comment] 2022-10-12 22:06
Hi,

We tried your suggestion and now the training doesn't hang! But we got the similar issue in the evaluation. And we noticed your suggestion in another [issue](https://github.com/google-research/smore/issues/10)  and follow the suggestion, but it still hangs. 

I really appreciate your help!

**Comment by hyren** [comment] 2022-10-12 22:21
hi, what's the script you used?

**Comment by Juanhui28** [comment] 2022-10-12 22:22
Hi, train_shallow_wikikgv2.sh  in the  training/vec_scripts folder.

**Comment by hyren** [comment] 2022-10-12 22:33
can you add the flag `--eval_async`?

**Comment by hyren** [comment] 2022-10-12 22:34
Just to make sure, you used the scripts in train_shallow_wikikgv2.sh and add the `--train_async_rw=False` flag?

**Comment by Juanhui28** [comment] 2022-10-12 23:54
Actually no, since if we add it we got the unrecognized arguments error.

**Comment by hyren** [comment] 2022-10-12 23:57
have you pulled the most recent commits?

**Comment by Juanhui28** [comment] 2022-10-13 03:16
Sorry we made some mistakes when we merged the code. Now we pulled the the latest code and it works for both training and evaluation!

Thank you so much!

**Closed as completed** 2022-10-13 04:36 UTC
